name: Frontend

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  frontend:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }} + node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure Mix
        run: |
          cp tests/frontend/package.json ./
          cp tests/frontend/appshell.mix.js ./
          cp tests/frontend/print.mix.js ./
      - name: Install Dependencies
        run: npm i
      - name: Theme Build
        run: npm run appshell
      - name: Print Build
        run: npm run print
