name: Frontend

on: [push]

jobs:
  frontend:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      CI: true
    strategy:
      matrix:
        node-version: [12.x, 16.x, 17.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Frontend Build ${{ matrix.os }} + node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
      - name: Configure Mix
        run: |
          cp tests/frontend/package.json ./
          cp tests/frontend/appshell.mix.js ./
          cp tests/frontend/print.mix.js ./
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
      - name: Theme Build
        env:
          NODE_OPTIONS: ${{ matrix.node-version == '17.x' && '--openssl-legacy-provider' || '' }}
        run: npm run appshell
      - name: Print Build
        env:
          NODE_OPTIONS: ${{ matrix.node-version == '17.x' && '--openssl-legacy-provider' || '' }}
        run: npm run print
